# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='Precio',
        ),
        migrations.AddField(
            model_name='libros',
            name='Sinopsis',
            field=models.TextField(null=True),
        ),
    ]
